name:                squealgen
version:             0.1.0.0
github:              "mwotton/squealgen"
license:             BSD3
author:              "Mark Wotton"
maintainer:          "mwotton@gmail.com"
copyright:           "2020 Mark Wotton"

extra-source-files:
- README.md
- ChangeLog.md
- squealgen
- squealgen.sql

# Metadata used when publishing your package
synopsis:            generate squeal types from an existing database
category:            Database
description:         Please see the README on GitHub at <https://github.com/mwotton/squealgen#readme>

dependencies:
- base >= 4.7 && < 5

# this is more or less a stub for testing purposes.
library:
  source-dirs: src
  dependencies:
  - squeal-postgresql
